# create  jenkins user
- name: Create jenkins user
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - include: /home/onest/IdeaProjects/setup_instance/aws_instance_setup/common/add-system-user.yaml
      vars:
        user: { name: "jenkins", sudo: true }

- name: Add public key to jenkins user's authorized_keys
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Copy keys
      authorized_key:
        user: jenkins
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCY5pqAcaYpBIQXgH6i/XvwcdRZfSo8rkjxJWa3bZc4HPQ6P0GhtEQ9F04fz8PhyHEz7mCP1DKlTsauIYbhweflIDQafLD7EVuXlUAPcI8u1oJPuP3ECqTKISySJ/7XahX9VniZy4CWzYrb3IQQdkj3urT1TBqB1EzneQNFyKz6YhH/XVtYUEAmZJXGjZTopiGqzYY/C+HH41yciS24o4tCsBua/VW3zFFBs455YMAnLZACr/VaCzQyX5oe71hAeg7t6rpLKzwp3KqtmvI1bd1kaL3IDNM6T6+U549xGoGH5QrBnNu8Gw8QVPEPGk/xIoij8riWtlRtURt294u7dOK9 onest@localhost.localdomain"
        #key: "{{ lookup('file', 'id_rsa.pub') }}"

- name: Copy ssh keys to jenkins user on master
  hosts: master
  become: yes
  gather_facts: no
  tasks:
    - name: Copy public key
      copy:
        src: id_rsa.pub
        dest: /home/jenkins/.ssh/id_rsa.pub
        owner: jenkins
        group: jenkins
        mode: 0700

- name: Install common tools
  become: yes
  gather_facts: no
  hosts: all
  tasks:
    - name: Install tools
      yum: name={{ item }} state=present
      with_items:
        - wget
        - git
        - bind-utils
        - expect
        - vim-enhanced
        - gnuplot
        - zip
        - unzip
        - bc

- name: Install OpenJDK, maven and ant
  become: yes
  gather_facts: no
  hosts: all
  tasks:
    - name: Install OpenJDK, maven and ant
      yum: name={{ item }} state=present
      with_items:
        - java-1.8.0-openjdk-devel
        - maven
        - ant

- name: Install Groovy
  become: yes
  gather_facts: no
  hosts: all
  tasks:
    - name: Download Groovy
      get_url:
        url: https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.12.zip
        dest: /tmp/groovy.zip
    - name: Install Groovy
      command: unzip -o /tmp/groovy.zip
      args:
        chdir: /opt
        creates: /opt/groovy-2.4.12
    - name: Create a common Groovy path
      file:
        src: /opt/groovy-2.4.12
        dest: /opt/groovy
        owner: root
        group: root
        state: link
    - name: Set access rights for Groovy executables
      file:
        path: /opt/groovy/bin
        state: directory
        recurse: yes
        mode: 0755

- name: Install Jenkins and HTTPD on master
  become: yes
  gather_facts: no
  hosts: all
  tasks:
    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: https://pkg.jenkins.io/redhat-stable
        repo_gpgcheck: no
    - name: Import Jenkins rpm GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: Install Jenkins package
      yum:
        name: jenkins
        state: present
    - name: Change Jenkins port to 8001
      replace:
        path: /etc/sysconfig/jenkins
        regexp: 'JENKINS_PORT="8080"'
        replace: 'JENKINS_PORT="8001"'
    - name: Start and enable Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
    - name: Install httpd package
      yum:
        name: httpd
        state: present
    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes